"""initial_schema

Revision ID: 96fb711c03f8
Revises: 
Create Date: 2026-04-28 01:57:47.323449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96fb711c03f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('rq_job_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'RETRYING', 'COMPLETED', 'FAILED', name='job_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('classification', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_classification'), 'jobs', ['classification'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_task_id'), 'jobs', ['task_id'], unique=True)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('vendor_id', sa.String(length=256), nullable=False),
    sa.Column('invoice_id', sa.String(length=256), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'invoice_id', name='uq_invoices_vendor_invoice')
    )
    op.create_index(op.f('ix_invoices_invoice_id'), 'invoices', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoices_job_id'), 'invoices', ['job_id'], unique=False)
    op.create_index(op.f('ix_invoices_vendor_id'), 'invoices', ['vendor_id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('vendor_id', sa.String(length=256), nullable=False),
    sa.Column('tracking_number', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('TRANSIT', 'DELIVERED', 'EXCEPTION', name='shipment_status'), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_job_id'), 'shipments', ['job_id'], unique=False)
    op.create_index(op.f('ix_shipments_tracking_number'), 'shipments', ['tracking_number'], unique=True)
    op.create_index(op.f('ix_shipments_vendor_id'), 'shipments', ['vendor_id'], unique=False)
    op.create_table('unclassified_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unclassified_events_job_id'), 'unclassified_events', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unclassified_events_job_id'), table_name='unclassified_events')
    op.drop_table('unclassified_events')
    op.drop_index(op.f('ix_shipments_vendor_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_tracking_number'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_job_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_invoices_vendor_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_job_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_jobs_task_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_classification'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
